on:
  push:
  workflow_dispatch:

name: ci

jobs:
  ci:
    runs-on: ubuntu-20.04
    name: ci
    steps:
      - uses: actions/checkout@v3.1.0
      - uses: ./
        with:
          greetee: 'Everybody'
